set_settings:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: hon
    settings:
      required: true
      example: |
        onOffStatus: "on"
        machMode: cool
        tempSel: 24
        windDirectionHorizontal: position_2
        windDirectionVertical: position_5
        muteStatus: "on"
        screenDisplayStatus: "off"
      selector:
        object:
