set_settings:
  target:
    device:
      integration: hon
  fields:
    settings:
      required: true
      example: |
        onOffStatus: "on"
        machMode: cool
        tempSel: 24
        windDirectionHorizontal: position_2
        windDirectionVertical: position_5
        muteStatus: "on"
        screenDisplayStatus: "off"
      selector:
        object:
