name: HACS Action

on:
  push:
    branches:
      - disabled-workflow
  pull_request:
    branches:
      - disabled-workflow

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
